name: CD Staging

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://test.biottic.com.co
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build and prepare assets
        run: |
          # Realizar el build
          pnpm run build
          
          # Verificar que el directorio dist/assets existe
          if [ ! -d "dist/assets" ]; then
            echo "Error: dist/assets directory not found"
            exit 1
          fi
        env:
          VITE_API_URL: 'https://test.biottic.com.co/api'
          
      - name: Add host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to Staging Server
        env:
          DEPLOY_HOST: ${{ secrets.SSH_HOST }}
          DEPLOY_USER: ${{ secrets.SSH_USER }}
          DEPLOY_PASS: ${{ secrets.SSH_PASS }}
        run: |
          tar -czf dist.tar.gz dist/
          sshpass -p "$DEPLOY_PASS" scp -o StrictHostKeyChecking=no dist.tar.gz $DEPLOY_USER@$DEPLOY_HOST:/tmp/
          sshpass -p "$DEPLOY_PASS" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            rm -rf /home/admin/web/test.biottic.com.co/public_html/*
            cd /home/admin/web/test.biottic.com.co/public_html
            tar xzf /tmp/dist.tar.gz --strip-components=1
            rm /tmp/dist.tar.gz
            
            # Verificar que los assets se copiaron correctamente
            if [ ! -d "assets" ]; then
              echo "Error: assets directory not found after deployment"
              exit 1
            fi
            
            # Ajustar permisos
            chown -R admin:admin .
            find . -type d -exec chmod 755 {} \;
            find . -type f -exec chmod 644 {} \;
            
            # Verificar los permisos de los assets
            ls -la assets/
          EOF
