name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Ejecutar cada domingo
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.biottic.com.co
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run SAST
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        
      - name: Run Dependency Check
        run: |
          pnpm audit
          
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: ${{ secrets.STAGING_API_URL }}
